version: "3.8"
services:
  mongodb:
    image: library/mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db

  app:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true

  mongoimport:
    image: library/mongo:latest
    container_name: rooms-import
    links:
      - mongodb
    volumes:
      - ./rooms.json:/data/rooms.json
    command: mongoimport -u "root" -p "123456" --authenticationDatabase "admin" --host mongodb --db airbnb --collection rooms --file /data/rooms.json --jsonArray

volumes:
  db:
